name: Busted Tests

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i 's|%placeholder%|${{github.workspace}}|g' ${{github.workspace}}/spec/Test.xml
      - run: cat ${{github.workspace}}/spec/Test.xml
      - name: Run Busted tests
        uses: demonnic/test-in-mudlet@v1.2
        with:
          testsDirectory: ${{ github.workspace }}/spec
          pretestPackage: ${{ github.workspace }}/spec/Test.xml
